/**
 * generated by Xtext 2.19.0
 */
package org.xtext.projet_idm.mydsl.myDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>ALGO</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.projet_idm.mydsl.myDsl.MyDslPackage#getALGO()
 * @model
 * @generated
 */
public enum ALGO implements Enumerator
{
  /**
   * The '<em><b>J48</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #J48_VALUE
   * @generated
   * @ordered
   */
  J48(0, "J48", "J48"),

  /**
   * The '<em><b>Naive Bayes</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NAIVE_BAYES_VALUE
   * @generated
   * @ordered
   */
  NAIVE_BAYES(1, "NaiveBayes", "NaiveBayes"),

  /**
   * The '<em><b>Classification Tree</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CLASSIFICATION_TREE_VALUE
   * @generated
   * @ordered
   */
  CLASSIFICATION_TREE(2, "ClassificationTree", "ClassificationTree"),

  /**
   * The '<em><b>SVM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SVM_VALUE
   * @generated
   * @ordered
   */
  SVM(3, "SVM", "SVM");

  /**
   * The '<em><b>J48</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #J48
   * @model
   * @generated
   * @ordered
   */
  public static final int J48_VALUE = 0;

  /**
   * The '<em><b>Naive Bayes</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NAIVE_BAYES
   * @model name="NaiveBayes"
   * @generated
   * @ordered
   */
  public static final int NAIVE_BAYES_VALUE = 1;

  /**
   * The '<em><b>Classification Tree</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CLASSIFICATION_TREE
   * @model name="ClassificationTree"
   * @generated
   * @ordered
   */
  public static final int CLASSIFICATION_TREE_VALUE = 2;

  /**
   * The '<em><b>SVM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SVM
   * @model
   * @generated
   * @ordered
   */
  public static final int SVM_VALUE = 3;

  /**
   * An array of all the '<em><b>ALGO</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ALGO[] VALUES_ARRAY =
    new ALGO[]
    {
      J48,
      NAIVE_BAYES,
      CLASSIFICATION_TREE,
      SVM,
    };

  /**
   * A public read-only list of all the '<em><b>ALGO</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ALGO> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>ALGO</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ALGO get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ALGO result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>ALGO</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ALGO getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ALGO result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>ALGO</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ALGO get(int value)
  {
    switch (value)
    {
      case J48_VALUE: return J48;
      case NAIVE_BAYES_VALUE: return NAIVE_BAYES;
      case CLASSIFICATION_TREE_VALUE: return CLASSIFICATION_TREE;
      case SVM_VALUE: return SVM;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ALGO(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ALGO
