/**
 * generated by Xtext 2.19.0
 */
package org.xtext.projet_idm.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.projet_idm.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/projet_idm/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.projet_idm.mydsl.myDsl.impl.MachineLearingGeneratorImpl <em>Machine Learing Generator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.MachineLearingGeneratorImpl
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getMachineLearingGenerator()
   * @generated
   */
  int MACHINE_LEARING_GENERATOR = 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE_LEARING_GENERATOR__OPERATIONS = 0;

  /**
   * The number of structural features of the '<em>Machine Learing Generator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE_LEARING_GENERATOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.projet_idm.mydsl.myDsl.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.OperationImpl
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 1;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.projet_idm.mydsl.myDsl.impl.CSVFileImpl <em>CSV File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.CSVFileImpl
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getCSVFile()
   * @generated
   */
  int CSV_FILE = 2;

  /**
   * The feature id for the '<em><b>L2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_FILE__L2 = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>L3</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_FILE__L3 = OPERATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>L4</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_FILE__L4 = OPERATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_FILE__FILE = OPERATION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>CSV File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_FILE_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.projet_idm.mydsl.myDsl.impl.SplitSetImpl <em>Split Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.SplitSetImpl
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getSplitSet()
   * @generated
   */
  int SPLIT_SET = 3;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPLIT_SET__VAR = 0;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPLIT_SET__SIZE = 1;

  /**
   * The feature id for the '<em><b>Strat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPLIT_SET__STRAT = 2;

  /**
   * The number of structural features of the '<em>Split Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPLIT_SET_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.projet_idm.mydsl.myDsl.impl.PredictImpl <em>Predict</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.PredictImpl
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getPredict()
   * @generated
   */
  int PREDICT = 4;

  /**
   * The feature id for the '<em><b>Algo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICT__ALGO = 0;

  /**
   * The number of structural features of the '<em>Predict</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.projet_idm.mydsl.myDsl.ALGO <em>ALGO</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet_idm.mydsl.myDsl.ALGO
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getALGO()
   * @generated
   */
  int ALGO = 5;

  /**
   * The meta object id for the '{@link org.xtext.projet_idm.mydsl.myDsl.STRAT <em>STRAT</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet_idm.mydsl.myDsl.STRAT
   * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getSTRAT()
   * @generated
   */
  int STRAT = 6;


  /**
   * Returns the meta object for class '{@link org.xtext.projet_idm.mydsl.myDsl.MachineLearingGenerator <em>Machine Learing Generator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Machine Learing Generator</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.MachineLearingGenerator
   * @generated
   */
  EClass getMachineLearingGenerator();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet_idm.mydsl.myDsl.MachineLearingGenerator#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.MachineLearingGenerator#getOperations()
   * @see #getMachineLearingGenerator()
   * @generated
   */
  EReference getMachineLearingGenerator_Operations();

  /**
   * Returns the meta object for class '{@link org.xtext.projet_idm.mydsl.myDsl.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.projet_idm.mydsl.myDsl.CSVFile <em>CSV File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CSV File</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.CSVFile
   * @generated
   */
  EClass getCSVFile();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet_idm.mydsl.myDsl.CSVFile#getL2 <em>L2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>L2</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.CSVFile#getL2()
   * @see #getCSVFile()
   * @generated
   */
  EReference getCSVFile_L2();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet_idm.mydsl.myDsl.CSVFile#getL3 <em>L3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>L3</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.CSVFile#getL3()
   * @see #getCSVFile()
   * @generated
   */
  EReference getCSVFile_L3();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.projet_idm.mydsl.myDsl.CSVFile#getL4 <em>L4</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>L4</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.CSVFile#getL4()
   * @see #getCSVFile()
   * @generated
   */
  EAttribute getCSVFile_L4();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet_idm.mydsl.myDsl.CSVFile#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>File</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.CSVFile#getFile()
   * @see #getCSVFile()
   * @generated
   */
  EAttribute getCSVFile_File();

  /**
   * Returns the meta object for class '{@link org.xtext.projet_idm.mydsl.myDsl.SplitSet <em>Split Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Split Set</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.SplitSet
   * @generated
   */
  EClass getSplitSet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet_idm.mydsl.myDsl.SplitSet#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.SplitSet#getVar()
   * @see #getSplitSet()
   * @generated
   */
  EAttribute getSplitSet_Var();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet_idm.mydsl.myDsl.SplitSet#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.SplitSet#getSize()
   * @see #getSplitSet()
   * @generated
   */
  EAttribute getSplitSet_Size();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet_idm.mydsl.myDsl.SplitSet#getStrat <em>Strat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Strat</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.SplitSet#getStrat()
   * @see #getSplitSet()
   * @generated
   */
  EAttribute getSplitSet_Strat();

  /**
   * Returns the meta object for class '{@link org.xtext.projet_idm.mydsl.myDsl.Predict <em>Predict</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predict</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.Predict
   * @generated
   */
  EClass getPredict();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet_idm.mydsl.myDsl.Predict#getAlgo <em>Algo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Algo</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.Predict#getAlgo()
   * @see #getPredict()
   * @generated
   */
  EAttribute getPredict_Algo();

  /**
   * Returns the meta object for enum '{@link org.xtext.projet_idm.mydsl.myDsl.ALGO <em>ALGO</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>ALGO</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.ALGO
   * @generated
   */
  EEnum getALGO();

  /**
   * Returns the meta object for enum '{@link org.xtext.projet_idm.mydsl.myDsl.STRAT <em>STRAT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>STRAT</em>'.
   * @see org.xtext.projet_idm.mydsl.myDsl.STRAT
   * @generated
   */
  EEnum getSTRAT();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.projet_idm.mydsl.myDsl.impl.MachineLearingGeneratorImpl <em>Machine Learing Generator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.MachineLearingGeneratorImpl
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getMachineLearingGenerator()
     * @generated
     */
    EClass MACHINE_LEARING_GENERATOR = eINSTANCE.getMachineLearingGenerator();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MACHINE_LEARING_GENERATOR__OPERATIONS = eINSTANCE.getMachineLearingGenerator_Operations();

    /**
     * The meta object literal for the '{@link org.xtext.projet_idm.mydsl.myDsl.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.OperationImpl
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.xtext.projet_idm.mydsl.myDsl.impl.CSVFileImpl <em>CSV File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.CSVFileImpl
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getCSVFile()
     * @generated
     */
    EClass CSV_FILE = eINSTANCE.getCSVFile();

    /**
     * The meta object literal for the '<em><b>L2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CSV_FILE__L2 = eINSTANCE.getCSVFile_L2();

    /**
     * The meta object literal for the '<em><b>L3</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CSV_FILE__L3 = eINSTANCE.getCSVFile_L3();

    /**
     * The meta object literal for the '<em><b>L4</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSV_FILE__L4 = eINSTANCE.getCSVFile_L4();

    /**
     * The meta object literal for the '<em><b>File</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSV_FILE__FILE = eINSTANCE.getCSVFile_File();

    /**
     * The meta object literal for the '{@link org.xtext.projet_idm.mydsl.myDsl.impl.SplitSetImpl <em>Split Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.SplitSetImpl
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getSplitSet()
     * @generated
     */
    EClass SPLIT_SET = eINSTANCE.getSplitSet();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPLIT_SET__VAR = eINSTANCE.getSplitSet_Var();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPLIT_SET__SIZE = eINSTANCE.getSplitSet_Size();

    /**
     * The meta object literal for the '<em><b>Strat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPLIT_SET__STRAT = eINSTANCE.getSplitSet_Strat();

    /**
     * The meta object literal for the '{@link org.xtext.projet_idm.mydsl.myDsl.impl.PredictImpl <em>Predict</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.PredictImpl
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getPredict()
     * @generated
     */
    EClass PREDICT = eINSTANCE.getPredict();

    /**
     * The meta object literal for the '<em><b>Algo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICT__ALGO = eINSTANCE.getPredict_Algo();

    /**
     * The meta object literal for the '{@link org.xtext.projet_idm.mydsl.myDsl.ALGO <em>ALGO</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet_idm.mydsl.myDsl.ALGO
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getALGO()
     * @generated
     */
    EEnum ALGO = eINSTANCE.getALGO();

    /**
     * The meta object literal for the '{@link org.xtext.projet_idm.mydsl.myDsl.STRAT <em>STRAT</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet_idm.mydsl.myDsl.STRAT
     * @see org.xtext.projet_idm.mydsl.myDsl.impl.MyDslPackageImpl#getSTRAT()
     * @generated
     */
    EEnum STRAT = eINSTANCE.getSTRAT();

  }

} //MyDslPackage
