/**
 * generated by Xtext 2.19.0
 */
package org.xtext.projet_idm.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Split Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projet_idm.mydsl.myDsl.SplitSet#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.projet_idm.mydsl.myDsl.SplitSet#getSize <em>Size</em>}</li>
 *   <li>{@link org.xtext.projet_idm.mydsl.myDsl.SplitSet#getStrat <em>Strat</em>}</li>
 * </ul>
 *
 * @see org.xtext.projet_idm.mydsl.myDsl.MyDslPackage#getSplitSet()
 * @model
 * @generated
 */
public interface SplitSet extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see org.xtext.projet_idm.mydsl.myDsl.MyDslPackage#getSplitSet_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link org.xtext.projet_idm.mydsl.myDsl.SplitSet#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(String)
   * @see org.xtext.projet_idm.mydsl.myDsl.MyDslPackage#getSplitSet_Size()
   * @model
   * @generated
   */
  String getSize();

  /**
   * Sets the value of the '{@link org.xtext.projet_idm.mydsl.myDsl.SplitSet#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(String value);

  /**
   * Returns the value of the '<em><b>Strat</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.projet_idm.mydsl.myDsl.STRAT}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strat</em>' attribute.
   * @see org.xtext.projet_idm.mydsl.myDsl.STRAT
   * @see #setStrat(STRAT)
   * @see org.xtext.projet_idm.mydsl.myDsl.MyDslPackage#getSplitSet_Strat()
   * @model
   * @generated
   */
  STRAT getStrat();

  /**
   * Sets the value of the '{@link org.xtext.projet_idm.mydsl.myDsl.SplitSet#getStrat <em>Strat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Strat</em>' attribute.
   * @see org.xtext.projet_idm.mydsl.myDsl.STRAT
   * @see #getStrat()
   * @generated
   */
  void setStrat(STRAT value);

} // SplitSet
