/**
 * generated by Xtext 2.19.0
 */
package org.xtext.projet_idm.mydsl;

import org.xtext.projet_idm.mydsl.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
