/**
 * generated by Xtext 2.19.0
 */
package org.xtext.projet_idm.mydsl.scoping;

import org.xtext.projet_idm.mydsl.scoping.AbstractMyDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MyDslScopeProvider extends AbstractMyDslScopeProvider {
}
