/*
 * generated by Xtext 2.19.0
 */
package org.xtext.projet_idm.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
