/*
 * generated by Xtext 2.19.0
 */
package org.xtext.projet_idm.mydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/projet_idm/mydsl/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
